### PR TITLE
Installer notebook to distribute dashboard

### PR DESCRIPTION
**Pull request by anhhchu**
* Add Installer Notebook to distribute dashboard in customer environment
* Update README with detail instructions

### CODE REVIEW

**Comment by dmoore247** [comment]
@anhhchu Can we remove the dashboard.json from your pull request and use the one in the main branch?

**Comment by dmoore247** [comment]
@anhhchu Can you find a way to resolve conflicts in the README.md for the PR?

**Comment by anhhchu** [comment]
Hi @dmoore247,
I can remove the json but the conflict in the README you might have to resolve

**Comment by anhhchu** [comment]
@dmoore247, conflict resolved. Can you review now?

**Comment by anhhchu** [comment]
@dmoore247, newest dashboard json is updated

**Pull request closed without merging**
